# Generated by Django 5.2.6 on 2025-09-22 14:37

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='دسته بندی')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='book.category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کتاب')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('translator', models.CharField(blank=True, max_length=100, null=True, verbose_name='مترجم')),
                ('rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='حجم')),
                ('book_type', models.CharField(choices=[('epub', 'EPUB'), ('pdf', 'PDF'), ('mobi', 'MOBI'), ('mp3', 'MP3'), ('wav', 'WAV')], max_length=4, verbose_name='نوع')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('is_discount', models.BooleanField(default=False, verbose_name='تخفیف دارد؟')),
                ('about', models.TextField(blank=True, null=True, verbose_name='معرفی کتاب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='درباره کتاب')),
                ('speaker', models.CharField(max_length=100, verbose_name='گوینده')),
                ('time', models.PositiveIntegerField(default=0, verbose_name='زمان')),
                ('is_transferable', models.BooleanField(default=False, verbose_name='قابلیت انتقال دارد؟')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audiobooks', to='book.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'صوتی',
                'verbose_name_plural': 'صوتی',
            },
        ),
        migrations.CreateModel(
            name='PrintedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کتاب')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('translator', models.CharField(blank=True, max_length=100, null=True, verbose_name='مترجم')),
                ('rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='حجم')),
                ('book_type', models.CharField(choices=[('epub', 'EPUB'), ('pdf', 'PDF'), ('mobi', 'MOBI'), ('mp3', 'MP3'), ('wav', 'WAV')], max_length=4, verbose_name='نوع')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('is_discount', models.BooleanField(default=False, verbose_name='تخفیف دارد؟')),
                ('about', models.TextField(blank=True, null=True, verbose_name='معرفی کتاب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='درباره کتاب')),
                ('collector', models.CharField(blank=True, max_length=100, null=True, verbose_name='گرد آورنده')),
                ('publisher', models.CharField(max_length=100, verbose_name='انتشارات')),
                ('year', models.IntegerField(verbose_name='سال انتشار')),
                ('pages', models.IntegerField(verbose_name='تعداد صفحه ها')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='book.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
    ]
